### ISSUE TITLE
Missing .visx file

### ISSUE THREAD

**Issue by M-Zuber** [nagits/TfsPendingChangesMargin#6]
When I click on the download link in the visual studio gallery I get the following error:
![image](https://cloud.githubusercontent.com/assets/4746537/4932691/b7d8fbbe-658c-11e4-9f8e-42f1a6f8d147.png)

In the meantime I downloaded the source from Github and compiled it myself, but I may not be able to do that on every machine that I want to use this very helpful extension on

**Comment by nagits** [comment]
I assume it can happen for a while after updating the publication on the Visual Studio Gallery.
It is a website problem, I am not able to change anything.
